module Path


let ace_clubs_path = "./KINS/Clubs_ACE.png"
let king_clubs_path = "./KINS/Clubs_K.png"
let queen_clubs_path = "./KINS/Clubs_Q.png"
let jack_clubs_path = "./KINS/Clubs_J.png"
let ten_clubs_path = "./KINS/Clubs_10.png"
let nine_clubs_path = "./KINS/Clubs_9.png"
let eight_clubs_path = "./KINS/Clubs_8.png"
let seven_clubs_path = "./KINS/Clubs_7.png"
let six_clubs_path = "./KINS/Clubs_6.png"
let five_clubs_path = "./KINS/Clubs_5.png"
let four_clubs_path = "./KINS/Clubs_4.png"
let three_clubs_path = "./KINS/Clubs_3.png"
let two_clubs_path = "./KINS/Clubs_2.png"

let ace_hearts_path = "./KINS/Hearts_ACE.png"
let king_hearts_path = "./KINS/Hearts_K.png"
let queen_hearts_path = "./KINS/Hearts_Q.png"
let jack_hearts_path = "./KINS/Hearts_J.png"
let ten_hearts_path = "./KINS/Hearts_10.png"
let nine_hearts_path = "./KINS/Hearts_9.png"
let eight_hearts_path = "./KINS/Hearts_8.png"
let seven_hearts_path = "./KINS/Hearts_7.png"
let six_hearts_path = "./KINS/Hearts_6.png"
let five_hearts_path = "./KINS/Hearts_5.png"
let four_hearts_path = "./KINS/Hearts_4.png"
let three_hearts_path = "./KINS/Hearts_3.png"
let two_hearts_path = "./KINS/Hearts_2.png"


let ace_spades_path = "./KINS/Spades_ACE.png"
let king_spades_path = "./KINS/Spades_K.png"
let queen_spades_path = "./KINS/Spades_Q.png"
let jack_spades_path = "./KINS/Spades_J.png"
let ten_spades_path = "./KINS/Spades_10.png"
let nine_spades_path = "./KINS/Spades_9.png"
let eight_spades_path = "./KINS/Spades_8.png"
let seven_spades_path = "./KINS/Spades_7.png"
let six_spades_path = "./KINS/Spades_6.png"
let five_spades_path = "./KINS/Spades_5.png"
let four_spades_path = "./KINS/Spades_4.png"
let three_spades_path = "./KINS/Spades_3.png"
let two_spades_path = "./KINS/Spades_2.png"


let ace_diamonds_path = "./KINS/Diamonds_ACE.png"
let king_diamonds_path = "./KINS/Diamonds_K.png"
let queen_diamonds_path = "./KINS/Diamonds_Q.png"
let jack_diamonds_path = "./KINS/Diamonds_J.png"
let ten_diamonds_path = "./KINS/Diamonds_10.png"
let nine_diamonds_path = "./KINS/Diamonds_9.png"
let eight_diamonds_path = "./KINS/Diamonds_8.png"
let seven_diamonds_path = "./KINS/Diamonds_7.png"
let six_diamonds_path = "./KINS/Diamonds_6.png"
let five_diamonds_path = "./KINS/Diamonds_5.png"
let four_diamonds_path = "./KINS/Diamonds_4.png"
let three_diamonds_path = "./KINS/Diamonds_3.png"
let two_diamonds_path = "./KINS/Diamonds_2.png"